kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-import
  namespace: trident
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-basic
