kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: san-import
  namespace: trident
spec:
  accessModes:
    - ROX
  resources:
    requests:
      storage: 1Gi
  storageClassName: san-basic
